project:
  type: website
  output-dir: docs
  resources:
    - functions/submit.js
    - images

website:
  title: "Pinpoint Strategies"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Services
        menu:
          - href: pages/pinpoint_analytics.qmd
            text: Pinpoint Analytics
          - href: pages/pinpoint_solutions.qmd
            text: Pinpoint Solutions
          - href: pages/pinpoint_thinking.qmd
            text: Pinpoint Thinking
      - href: pages/about.qmd
        text: About
      - href: pages/contact.qmd
        text: Contact

    right:
      - icon: github
        text: GitHub
        href: https://github.com/pinpointstrategies
        aria-label: GitHub
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/jonathan-sidi-397a4036/
      - icon: envelope
        text: Email
        href: "mailto:support@pinpointstrategies.io"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

