project:
  type: website
  output-dir: docs

website:
  title: "Pinpoint Strategies"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: vision.qmd
        text: Vision
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

