on:
  workflow_dispatch:
  push:
    branches: dev

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html # If set, it will be equivalent to `quarto render --to html`

      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'website'
          directory: '/docs' # or _site or any other directory you used as project's output-dir in `_quarto.yml`
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
